include::../begriffe.adoc[]

== {title-entwicklerdoku}

include::zusammenfassung.adoc[]

=== Versionierung

Durch die Versionierung der Anwendung können verschiedene Anwendungsstände leichter auseinandergehalten werden.
In diesem Projekt werden zwei Arten der Versionierung unterschieden:

Version des Backends::
Beschreibt den Entwicklungsstand der Gesamtanwendung.
Bei jeder Aktualisierung, egal ob Rechtschreibkorrektur, Update einer Abhängigkeit oder einem großen neuen Feature
wird die Versionsnummer der Anwendung erhöht.
Version der APIs::
Das Backend bietet externe Schnittstellen an, über die es genutzt werden kann.
Jede dieser Schnittstellen verfügt über eine eigene Versionierung, welche zum Ziel hat,
Nutzer jener Schnittstellen nicht zu brechen.

==== Versionierung des Backends

Die Anwendung wird mittels https://semver.org/lang/de/[Semver] versioniert.
Versionen können hier also in Versionsnummern aus Major, Minor und Patch angegeben werden.

Die aktuelle Version des Backends ist in der `Cargo.toml` angegeben.
Sie erhöht sich bei *jeder* Änderung.
Diese Erhöhung geschieht automatisch durch das Build-System in Form der Patch-Versionsnummer.

Die Major- und Minor-Versionsnummern werden explizit in Form von Github-Releases beschrieben und bedeuten immer
ein Deployment auf die Produktionsumgebung.

Die Major- und Minor-Version beschreibt also den aktuellen Release.
Die Patch-Versionsnummer beschreibt hingegen, welche Version der Anwendung innerhalb des aktuellen Releases vorliegt.

===== Automatische Patch-Versionen

Bei jeder Änderung auf Main (i.d.R. ausgelöst durch zusammengeführte Pull Requests) erhöht das Build-System
automatisch die Patch-Versionsnummer um 1.
Da die APIs sicherstellen sollen, keine Breaking Changes zu verursachen, kann hier auch bei großen Änderungen
die Patch-Version verwendet werden.

===== Produktiv-Deployments

Soll die Anwendung auf der Produktionsumgebung aktualisiert werden, muss in Github ein Release mit Tag angelegt werden.
Während der Release-Name frei wählbar ist (im Regelfall aber die Versionsnummer enthalten sollte), muss der Tag
ein festgelegtes Format erfüllen: `v__MAJOR__._MINOR_`.

So könnte ein Release-Tag beispielsweise `v1.5` lauten.
Sobald dieser Tag gesetzt wurde, setzt das Build-System die Patch-Version auf `0` und aktualisiert die Versionsnummer
in der entsprechenden Projektdatei über einen separaten Commit.

==== Versionierung der APIs

Die externen Schnittstellen der Anwendung folgen einer eigenen, vereinfachten Versionierung.
Die Versionierung richtet sich hierbei nur nach Breaking Changes.
Sobald in einer Schnittstelle ein Breaking Change auftritt (Entfernen oder Ändern eines bestehenden Endpunkts),
muss eine neue Version der entsprechenden Schnittstelle daneben gestellt werden.
Diese enthält einen eigenen Endpunkt, sodass Anwender der Schnittstelle zu einem beliebigen Zeitpunkt umstellen können.

Die parallel laufenden Schnittstellen müssen ansonsten beide gewartet werden.
Zu einem beliebigen Zeitpunkt — das kann direkt beim Erstellen der neuen Version, aber auch nach 2 Jahren oder nie sein
— können wir eine Version einer Schnittstelle (oder eine Schnittstelle selbst) als deprecated markieren.
Diese Markierung muss mit einem entsprechenden Datumskommentar ergänzt werden.
Wir garantieren, den Endpunkt für weitere 3 Monate aktiv und lauffähig zu halten, bevor wir ihn abschalten.

==== Versionierung der Dokumentation

Die Dokumentation wird *immer* analog zur Anwendung aktualisiert.
Ihre Versionsnummer ist in ihrer `package.json` festgehalten.
