on:
  issue_comment:
    types: [created]

jobs:
  fast_forward_job:
    name: Fast Forward
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/fast-forward')
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4.2.2
      - name: Fast Forward PR
        uses: endre-spotlab/fast-forward-js-action@2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          success_message: "Stand von Branch ***target_base*** auf ***source_head*** aufgesetzt."
          failure_message: "Fast Forward nicht möglich. Bitte manuell rebasen!"