name: PR testen

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: Tests ausführen
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4.2.2

      - name: Abhängigkeiten installieren
        run: 'cargo build --locked'

      - name: Alle Tests ausführen
        run: 'cargo test'

  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
